/**
 * Public engine API.
 *
 * The engine is headless: it runs in the worker in production and directly in
 * tests, and depends on no DOM, React, storage or network facility
 * (Technical Specification 2, 4.1, 16).
 */
export {
  beginTransaction,
  commit,
  createEngineHost,
  createRecentRequests,
  ENGINE_VERSION,
  InvariantFailure,
  NoCampaignError,
  RECENT_REQUEST_LIMIT,
  runCommand,
} from '@engine/application';
export type {
  CommandRequest,
  CommandResult,
  CommitResult,
  EngineHost,
  EngineHostOptions,
  RecentRequests,
  Transaction,
} from '@engine/application';
export {
  authoritativeView,
  CAMPAIGN_ID_PATTERN,
  CAMPAIGN_SEED_PATTERN,
  CAMPAIGN_STATE_VERSION,
  campaignStateHash,
  createCampaign,
  deriveCampaignId,
  draftOf,
  drawChance,
  drawIntegerInRange,
  drawUnitInterval,
  entityIdOf,
  isCampaignId,
  isEntityId,
  MAX_DISPLAY_NAME_LENGTH,
  MAX_SCHEDULE_HORIZON_MS,
  MAX_SIMULATION_TIME_MS,
  PROJECTION_TOPICS,
  RANDOM_STREAMS,
  seedStreams,
  validateCampaign,
} from '@engine/domain';
export type {
  CampaignDraft,
  CampaignId,
  MutableRandomStreams,
  CampaignState,
  DomainEvent,
  DomainEventKind,
  DomainEventParams,
  EntityId,
  InvariantIssue,
  ProjectionTopic,
  RandomStreamName,
  RandomStreams,
  SchedulerEntry,
  SchedulerState,
  TimeState,
} from '@engine/domain';
export {
  frameProjection,
  sessionProjection,
  stateHashProjection,
} from '@engine/projections';
export {
  advanceTime,
  cancelBoundariesOwnedBy,
  cancelBoundary,
  nextBoundary,
  scheduleBoundary,
  takeBoundaryDue,
} from '@engine/simulation';
export type {
  AdvanceOutcome,
  BoundaryResolver,
  BoundaryResolvers,
  ScheduleRequest,
  SimulationContext,
} from '@engine/simulation';
export {
  ContentIntegrityError,
  ContentLookupError,
  DAMAGE_TYPES,
  DEFENSE_LAYERS,
  HARDPOINT_KINDS,
  ITEM_CATEGORIES,
  MARKET_SUPPLY_KINDS,
  MODULE_CATEGORIES,
  NPC_ROLES,
  RULE_GROUPS,
  SITE_KINDS,
  SLOT_KINDS,
  STATION_SERVICES,
} from '@engine/ports';
export type {
  AmmunitionDefinition,
  CapacitorModuleDefinition,
  CombatRules,
  ContentIdentity,
  ContentRepository,
  DamageProfile,
  DamageType,
  DefenseLayer,
  EconomyRules,
  EncounterDefinition,
  HullDefinition,
  ItemDefinition,
  LootTableDefinition,
  MarketListingDefinition,
  ModuleCategory,
  ModuleDefinition,
  NpcProfileDefinition,
  PropulsionModuleDefinition,
  RepairModuleDefinition,
  ResistanceModuleDefinition,
  RulesContent,
  SiteDefinition,
  StationDefinition,
  SystemDefinition,
  TimeRules,
  TradeableDefinition,
  TurretModuleDefinition,
} from '@engine/ports';
