/**
 * Public engine API.
 *
 * The engine is headless: it runs in the worker in production and directly in
 * tests, and depends on no DOM, React, storage or network facility
 * (Technical Specification 2, 4.1, 16).
 */
export {
  beginTransaction,
  captureSnapshot,
  commit,
  createEngineHost,
  createRecentRequests,
  createSaveService,
  ENGINE_VERSION,
  envelopeChecksum,
  InvariantFailure,
  isSealed,
  loadSave,
  migrateSave,
  NoCampaignError,
  RECENT_REQUEST_LIMIT,
  runCommand,
  SAVE_MIGRATIONS,
  saveIdOf,
} from '@engine/application';
export type {
  CaptureInput,
  CommandRequest,
  CommandResult,
  CommitResult,
  EngineHost,
  EngineHostOptions,
  LoadContext,
  LoadFailure,
  LoadResult,
  LoadSuccess,
  MigratableSave,
  MigrationResult,
  RecentRequests,
  ResumeResult,
  SaveMigration,
  SaveService,
  SaveServiceOptions,
  Transaction,
} from '@engine/application';
export {
  authoritativeView,
  campaignDefinitionReferences,
  CAMPAIGN_ID_PATTERN,
  CAMPAIGN_SEED_PATTERN,
  CAMPAIGN_STATE_VERSION,
  campaignStateHash,
  bulkQuote,
  createCampaign,
  deriveCampaignId,
  draftOf,
  drawChance,
  drawIntegerInRange,
  drawUnitInterval,
  entityIdOf,
  isCampaignId,
  isEntityId,
  MAX_DISPLAY_NAME_LENGTH,
  MAX_SCHEDULE_HORIZON_MS,
  MAX_SIMULATION_TIME_MS,
  listingDefinition,
  PROJECTION_TOPICS,
  RANDOM_STREAMS,
  readCampaignState,
  seedStreams,
  unitQuote,
  validateCampaign,
} from '@engine/domain';
export type {
  CampaignDraft,
  CampaignId,
  CampaignReadFailure,
  CampaignReadResult,
  CampaignReadSuccess,
  CampaignState,
  CreateCampaignInput,
  MutableRandomStreams,
  DomainEvent,
  DomainEventKind,
  DomainEventParams,
  EntityId,
  InvariantIssue,
  ProjectionTopic,
  RandomStreamName,
  RandomStreams,
  SchedulerEntry,
  SchedulerState,
  TimeState,
  BulkQuote,
  EconomyState,
  FormulaTrace,
  MarketListingState,
  StationEconomyState,
  UnitQuote,
} from '@engine/domain';
export {
  frameProjection,
  sessionProjection,
  stateHashProjection,
} from '@engine/projections';
export {
  advanceTime,
  cancelBoundariesOwnedBy,
  cancelBoundary,
  nextBoundary,
  resolveEconomyHour,
  scheduleBoundary,
  takeBoundaryDue,
} from '@engine/simulation';
export type {
  AdvanceOutcome,
  BoundaryResolver,
  BoundaryResolvers,
  ScheduleRequest,
  SimulationContext,
} from '@engine/simulation';
export {
  ContentIntegrityError,
  ContentLookupError,
  DAMAGE_TYPES,
  DEFAULT_SAVE_RETENTION,
  DEFAULT_SLOT_ID,
  DEFENSE_LAYERS,
  HARDPOINT_KINDS,
  ITEM_CATEGORIES,
  MARKET_SUPPLY_KINDS,
  MODULE_CATEGORIES,
  NPC_ROLES,
  RULE_GROUPS,
  SAVE_FORMAT_VERSION,
  SAVE_KINDS,
  SAVE_LIMITS,
  SaveStoreError,
  summaryOf,
  SITE_KINDS,
  SLOT_KINDS,
  STATION_SERVICES,
} from '@engine/ports';
export type {
  AmmunitionDefinition,
  CapacitorModuleDefinition,
  CombatRules,
  ContentIdentity,
  ContentRepository,
  DamageProfile,
  DamageType,
  DefenseLayer,
  EconomyRules,
  EncounterDefinition,
  HullDefinition,
  ItemDefinition,
  LootTableDefinition,
  MarketListingDefinition,
  ModuleCategory,
  ModuleDefinition,
  NpcProfileDefinition,
  PropulsionModuleDefinition,
  RepairModuleDefinition,
  ResistanceModuleDefinition,
  RulesContent,
  SaveEnvelope,
  SaveKind,
  SaveRetention,
  SaveStore,
  SaveStoreErrorReason,
  SaveSummary,
  SaveWriteRequest,
  SiteDefinition,
  SlotManifest,
  StationDefinition,
  StorageReport,
  SystemDefinition,
  TimeRules,
  TradeableDefinition,
  TurretModuleDefinition,
} from '@engine/ports';
