/**
 * Ports the engine depends on (Technical Specification 4.1, 4.3).
 *
 * A port is an interface the engine owns and an adapter implements. The
 * direction never reverses: the engine does not import an adapter, and an
 * adapter does not reach into the engine's domain.
 */
export {
  AUDIO_CHANNELS,
  AUDIO_WAVEFORMS,
  DAMAGE_TYPES,
  DEFENSE_LAYERS,
  GUIDANCE_MOVEMENT_ORDERS,
  GUIDANCE_SURFACES,
  HARDPOINT_KINDS,
  ITEM_CATEGORIES,
  MARKET_SUPPLY_KINDS,
  MODULE_CATEGORIES,
  NOTIFICATION_CATEGORIES,
  NOTIFICATION_REPEATS,
  NOTIFICATION_SEVERITIES,
  NPC_ROLES,
  SITE_KINDS,
  SLOT_KINDS,
  STATION_SERVICES,
} from './content/definitions.ts';
export type {
  AmmunitionDefinition,
  AudioChannel,
  AudioCueDefinition,
  AudioNoteDefinition,
  AudioWaveform,
  CapacitorModuleDefinition,
  DamageProfile,
  DamageType,
  DefenseLayer,
  EncounterDefinition,
  EncounterSpawnDefinition,
  GuidanceChainDefinition,
  GuidanceMovementOrder,
  GuidancePredicate,
  GuidancePredicateKind,
  GuidanceStepDefinition,
  GuidanceSurface,
  HardpointKind,
  HullDefinition,
  ItemCategory,
  ItemDefinition,
  LayerDefinition,
  LootEntryDefinition,
  LootTableDefinition,
  MarketListingDefinition,
  MarketSupplyKind,
  ModuleCategory,
  ModuleDefinition,
  NotificationCategory,
  NotificationDefinition,
  NotificationRepeat,
  NotificationSeverity,
  NotificationTrigger,
  NotificationTriggerKind,
  NpcProfileDefinition,
  NpcRole,
  PropulsionModuleDefinition,
  RepairModuleDefinition,
  ResistanceModuleDefinition,
  ResistanceProfile,
  SiteDefinition,
  SiteKind,
  SlotKind,
  StationDefinition,
  StationService,
  SystemDefinition,
  TradeableDefinition,
  TurretModuleDefinition,
} from './content/definitions.ts';
export { ContentIntegrityError, ContentLookupError } from './content/repository.ts';
export {
  DEFAULT_SAVE_RETENTION,
  DEFAULT_SLOT_ID,
  isSaveKind,
  SAVE_FORMAT_VERSION,
  SAVE_KINDS,
  SAVE_LIMITS,
  SaveStoreError,
  summaryOf,
} from './persistence/saves.ts';
export type {
  SaveEnvelope,
  SaveKind,
  SaveRetention,
  SaveStore,
  SaveStoreErrorReason,
  SaveSummary,
  SaveWriteRequest,
  SlotManifest,
  StorageReport,
} from './persistence/saves.ts';
export type { ContentIdentity, ContentRepository } from './content/repository.ts';
export { RULE_GROUPS } from './content/rules.ts';
export type {
  CombatRules,
  EconomyRules,
  NavigationRules,
  NpcRoleRules,
  RuleGroup,
  RulesContent,
  StartingFitEntry,
  TimeRules,
} from './content/rules.ts';
